language: python

python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy'

install:
    - 'pip install --upgrade -r requirements.txt'
    - 'pip install --upgrade -r requirements_test.txt'

script:
    - 'python setup.py test'
