language: python

python:
    - '2.5'
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - 'pypy'

install:
    - 'sudo pip install -r requirements.txt --use-mirrors'
    - 'sudo pip install -r requirements_test.txt --use-mirrors'

script:
    - 'python setup.py test'
