language: python

python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy'

install:
    - 'pip install flake8'
    - 'pip install -r requirements.txt'
    - 'pip install -r requirements_test.txt'

matrix:
  include:
  - python: '3.6'
    env: VERIFY_ENDPOINTS=True

before_script: "flake8 wargaming examples"

script:
    - 'python setup.py test'
